// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.10.1_magicast@0.5.3_pinia@3.0.4_typescript@5.9.3_vue@3.5.38_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.10.1_magicast@0.5.3_pinia@3.0.4_typescript@5.9.3_vue@3.5.38_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7.3.5_@types+node@22.20.0_jiti@2.7.0_lightningcss@1.32.0_terser@5.4_2baawt6wefhxa4mitzxkpw6tji/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7.3.5_@types+node@22.20.0_jiti@2.7.0_lightningcss@1.32.0_terser@5.4_2baawt6wefhxa4mitzxkpw6tji/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parser@7.29.7_db0@0.3.4_embla-carousel@8.6.0_idb-keyval@6.2.5_ioredis@5_qafyupswdnhny4vs4hpge4rj2i/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.3/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.3/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.3_vite@7.3.5_@types+node@22.20.0_jiti@2.7.0_lightningcss@1.32._3p5k22sb5yv2pwwguutgroyjqa/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@22.20.0_@vue+compiler-sfc@3.5.38_cac@6.7.14_db0_kj7woc27ta7hcyyzbeofgipqpq/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../plugins/auth.client")> &
  InjectionType<typeof import("../../plugins/pinia-persistedstate.client")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
